/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [diarienr]
      ,[atgardsnr]
      --,[ordningsnr]
      ,[atgard_typ]
      --,[bekraft_dat]
      --,[bevak_dat]
      ,[usrsign_reg]
      ,[usrsign_handl]
      ,[atgard_text]
      --,[u_atgard_text]
      --,[kund_kod_pre]
      --,[kund_kod]
      ,[kund_namn]
      ,[kund_gadr1]
      ,[kund_gadr2]
      ,[kund_postnr]
      ,[kund_padr]
      --,[u_kund_namn]
      --,[u_kund_gadr2]
      ,[ink_utg]
      ,[ink_dat]
      --,[dokid] -- Varför är den tom? Behövs ju ändå inte egentligen när d_assoc_dok
      ,[utg_dat]
      --,[remiss_finns]
      --,[personfakta_finns]
      --,[agare_usrsign]
      --,[grp_kod]
      --,[agare_beh]
      --,[grupp_beh]
      ,[andra_beh]
      --,[extern_ref]
      ,[reg_dat]
      ,[dok_finns] --Intressant? Kan ju skippa del av skript med det...
      --,[fri_dat]
      ,[enhet_kod]
      --,[atgard_fritext1]
      --,[u_atgard_fritext1]
      --,[atgard_kat1]
      --,[atgard_kat2]
      --,[atgard_kat3]
      --,[atgard_kat4]
      ,[mod_dat]
      --,[diarieford]
      --,[start_datum]
      --,[slut_datum]
      --,[atgard_status]
      --,[aktivitetsnr]
      --,[dok_mall]
      --,[lagrum_text]
      --,[giltig_dat_from]
      --,[giltig_dat_tom]
      --,[agare_kod]
      --,[obligatorisk]
      --,[usrsign_senast]
FROM [jvp].[dbo].[atgard]
WHERE ( atgard.diarieford = 'J' OR atgard.diarieford = 'A')
ORDER BY diarienr, atgardsnr;